CREATE TABLE estado(
id BIGINT NOT NULL AUTO_INCREMENT,
nome VARCHAR(60) NOT NULL,

PRIMARY KEY (id)
)ENGINE=INNODB DEFAULT CHARSET=utf8;

ALTER TABLE cidade ADD COLUMN estado_id BIGINT NOT NULL;

ALTER TABLE cidade ADD CONSTRAINT fk_cidade_estado
FOREIGN KEY (estado_id) REFERENCES estado(id);

ALTER TABLE cidade DROP COLUMN nome_estado;

ALTER TABLE cidade CHANGE nome_cidade nome VARCHAR(80) NOT NULL;
